name: streamsync
description: StreamSync Lite - Video Learning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.1.2
  
  # Video Player
  youtube_player_flutter: ^9.0.0
  
  # UI & Utilities
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_slidable: ^4.0.3
  share_plus: ^7.2.1
  fluttertoast: ^8.2.4
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Permission
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  drift_dev: ^2.14.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

